name: first
on: push
jobs:
    firstjob:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: welcome
              run: |
               echo "welcome"
               ls -lrta
               cat README.md
            - name: cowsay
              run: cowsay -f dragon "Hello" >> dragon.txt